### ISSUE TITLE
automatic deployment

### ISSUE THREAD

**Issue by ppxasjsm** [chryswoods/siremol.org#15]
Is the automatic deployment still working for this?

**Comment by ppxasjsm** [comment]
To be more precise, I updated some of the somd tutorials because they weren't correct anymore, but they don't appear.

**Comment by ppxasjsm** [comment]
@chryswoods, the automatic deployment doesn't seem to work anymore. I have updated quite a bit of the online tutorials for somd over the last few weeks, if you could upload that at some point in the near future to the website that would be great thanks!

**Comment by chryswoods** [comment]
Hi @toni. Yes, the automatic deployment has failed because of changes that Xilo have made to their PhP policy. I'm currently having to deploy manually, and will have automatic deployment working as part of the new CI/CD service I am building to replace travis (which is now too small for Sire). I have rebuilt and am redeploying now (once the tgz uploads from my hotel via the Bristol VPN)

**Comment by ppxasjsm** [comment]
Great thanks alot! Have a lovely Sunday!
